### PR TITLE
Update Staff, Club and RTI Page and Correction in Navbar Buttons

### PR DESCRIPTION
**Pull request by Jagmohan-Dixit**

### CODE REVIEW

**Comment by dinskid** [comment]
- Please add padding on the buttons on the navbar without submenus
- Content must be horizontally centered in RTI pages
- The cards of the director and the registrar could be made to have the same height
Please check the above and let me know if there is any issue. Thank you

**Comment by dinskid** [comment]
Hey, sorry, I couldn't get to it earlier. Can you please fix the merge conflict? Thanks

**Comment by Jagmohan-Dixit** [comment]
Ok I will do it asap

**Comment by dinskid** [comment]
image
@Jagmohan-Dixit It is still not centered for me. I even tried refreshing a bunch of times. Can you please take a look?

**Comment by Jagmohan-Dixit** [comment]
In which page it is?

**Comment by dinskid** [comment]
@Jagmohan-Dixit can you please fix the merge conflicts?

**Comment by Jagmohan-Dixit** [comment]
I will do it

**Comment by dinskid** [comment]
Merging after review at [http://iiittjaggu.surge.sh/](http://iiittjaggu.surge.sh/)

**Pull request merged**
