### PR TITLE
Updated notices.json

### PR DESCRIPTION
**Pull request by Emperor-Kautilya**

### CODE REVIEW

**Comment by fahad-israr** [comment]
Merge conflict !!!
@dinskid  have a look at this once.

**Comment by dinskid** [comment]
Yes, the format has changed. I guess I'll ask @Emperor-Kautilya to pull the latest and merge the dates from the old json file

**Comment by fahad-israr** [comment]
> Yes, the format has changed. I guess I'll ask @Emperor-Kautilya to pull the latest and merge the dates from the old json file

That'd be great :)

**Comment by dinskid** [comment]
Closing this as the format has changed in the new json files. @Emperor-Kautilya can update the json files and then in another PR can put in the dates (as the current version of the site works even without the dates)

**Pull request closed without merging**
