### PR TITLE
update footer

### PR DESCRIPTION
**Pull request by sarthak503**
Changes can be confirm here : https://iiitts.surge.sh/
Added "Last Updated : {date/time at which last commit was made}" line in footer section.

### CODE REVIEW

**Comment by dinskid** [comment]
Can you please center the 'last updated' line?
Additionally, whenever the network call to the API to set the date fails, the line displays the current UTC time as the last updated. This is misleading, Instead of that, some other line like "Error fetching last updated time" could be better. Also, it could show some loader - maybe just the text "Loading..." while the network call is being made.

**Comment by sarthak503** [comment]
Fixed the styling part. Also removed api and used preval macros for the same.

**Comment by sarthak503** [comment]
added the PIO (Public Information Officers) page, created the path for the same

**Comment by dinskid** [comment]
If I have understood things correctly, this method of using a preval macro gives the build time and not the last updated time. In my opinion, it should be the time when some content was updated - the information/the presentation, and hence I felt it could be the last commit time. However, this solution doesn't show the time of the git commit but rather the build time. Can you get clarification from @anoopjt before we move with this?

**Comment by sarthak503** [comment]
Yes, I checked it, it is not showing the last commit time. It is displaying the last build time. In that case, as far as I know, there are two ways, First way is to use the GitHub APIs for fetching the last commit time. But the problem is that it has some API rate limits so many times it won't even display the time. Second way is to do it manually every time a commit is made. There may be some other ways as well which I may not be aware off.

**Pull request closed without merging**
