### PR TITLE
Update Pages

### PR DESCRIPTION
**Pull request by mayank2021**
- Update Staff Page
- Merge admission contact, admission fee structure and admission form into single admission page
- Made Pg Page
- Made Ug Page
- Made Doctoral Page
- All the pages given above have the latest updated content

### CODE REVIEW

**Comment by dinskid** [comment]
The updated pages do not have a footer. Was that a design choice? If so, we should make things uniform across pages. If it was a mistake, can you add the footers?

**Comment by mayank2021** [comment]
@dinskid It was a mistake and I will add the footer asap. Sorry for the inconvenience

**Comment by mayank2021** [comment]
@dinskid I added the footer section, have a look

**Comment by dinskid** [comment]
Looks good. I'll merge it. Thank you

**Pull request merged**
